export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE';
export const GET_PRODUCT_NAME = 'GET_PRODUCT_NAME';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';
export const CLEAN_PRODUCT_DETAIL = "CLEAN_PRODUCT_DETAIL";
export const GET_ALL_SELECTS = 'GET_ALL_SELECTS';
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_BRANDS = "GET_BRANDS";
export const GET_FILTROS = "GET_FILTROS";
export const TOGGLE_DARK_MODE = "TOGGLE_DARK_MODE";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const SET_ACCESS = "SET_ACCESS"
export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOG_OUT = 'USER_LOG_OUT'
export const FINISH_PURCHASE = 'FINISH_PURCHASE'
export const GET_PURCHASE_USER = 'GET_PURCHASE_USER'
export const GET_USER_CART = 'GET_USER_CART'
export const CLEAN_USER_CART = 'CLEAN_USER_CART'

//actions Review

export const FETCH_REVIEWS_REQUEST = 'FETCH_REVIEWS_REQUEST';
export const FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS';
export const FETCH_REVIEWS_FAILURE = 'FETCH_REVIEWS_FAILURE';

export const CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST';
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const CREATE_REVIEW_FAILURE = 'CREATE_REVIEW_FAILURE';

export const UPDATE_REVIEW_REQUEST = 'UPDATE_REVIEW_REQUEST';
export const UPDATE_REVIEW_SUCCESS = 'UPDATE_REVIEW_SUCCESS';
export const UPDATE_REVIEW_FAILURE = 'UPDATE_REVIEW_FAILURE';

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAILURE = 'DELETE_REVIEW_FAILURE';
